name: hy_rx_bloc
description: A new Flutter package.
version: 2.1.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^2.1.0
  hy_rx: ^2.0.0

  rxdart: ^0.27.5

dev_dependencies:
  test: ^1.16.8