name: hy_rx_bloc
description: A new Flutter package.
version: 1.0.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^1.0.0
  hy_rx: ^1.0.0

  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.16.8