name: hy_rx_bloc
description: A new Flutter package.
version: 0.0.1
homepage: http://a.gitlab.local:10080/flutter/hy

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:
  hy: ^0.0.2
  hy_rx: ^0.0.1

  rxdart: ^0.24.1

dev_dependencies:
  test: ^1.15.3