name: hy_logger
description: logger package.
version: 0.0.1
homepage: http://a.gitlab.local:10080/flutter/hy

environment:
  sdk: ">=2.9.0 <3.0.0"

dependencies:

  hy: ^0.0.2

  logger: ^0.9.4

dev_dependencies:
  test: ^1.15.3