name: hy_logger
description: logger package.
version: 1.0.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^1.0.0
  logger: ^1.0.0

dev_dependencies:
  test: ^1.16.8