name: hy_rx
description: A new Flutter package.
version: 1.0.0
homepage: http://a.gitlab.local:10080/flutter/hy

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.26.0

dev_dependencies:
  test: ^1.16.8