name: hy_rx
description: A new Flutter package.
version: 2.0.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  rxdart: ^0.27.5

dev_dependencies:
  test: ^1.16.8