name: hy_injector
description: hy's ioc container implement.
version: 1.0.1
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^1.0.0
  injector: ^2.0.0

dev_dependencies:
  test: ^1.16.8