name: hy_crashlytics
description: A new Flutter package project.
version: 1.0.0
homepage: http://a.gitlab.local:10080/flutter/hy

environment:
  sdk: ">=2.15.1 <3.0.0"

dev_dependencies:
  test: ^1.16.8