name: hy_protobuf
description: protobuf package.
version: 1.0.1
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

  fixnum: ^1.0.0
  protobuf: ^2.0.0

dev_dependencies:
  test: ^1.16.8