name: hy_test
description: hy test package project.
version: 1.0.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^2.0.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.8