name: hy_pinyin
description: Chinese character conversion pinyin library.Accurate and complete Chinese character dictionary.Fast conversion.
version: 2.0.0
homepage: https://github.com/zqhy/flutter

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  hy: ^2.0.2
  lpinyin: ^2.0.3

dev_dependencies:
  test: ^1.20.1
